# Sorting

In [5]:
import time
import numpy as np
np.random.seed(0)
import random

In [46]:
data = np.random.randint(1,10000,17000)

### Insertion Sort

In [7]:
def insertion_sort(arr):
    start = time.time()
    for i in range(1, len(arr)): 
        temp = arr[i]       
        j = i-1
        while j >= 0 and temp< arr[j] :
                arr[j + 1] = arr[j]
                j -= 1
        arr[j + 1] = temp

    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr

In [8]:
arr= insertion_sort(data)

The time of execution of above program is : 29337.440967559814 ms for a size of  17000


In [9]:
arr

array([   1,    1,    1, ..., 9999, 9999, 9999])

In [51]:
dt=np.random.randint(1,10000,10)

In [11]:
a= insertion_sort(dt)

The time of execution of above program is : 1.0020732879638672 ms for a size of  100


### Merge Sort

In [12]:
def merge(arr):
    if len(arr) > 1:
         
        mid = len(arr)//2         
        left = arr[:mid] 
        right = arr[mid:] 
        
        merge(left) 
       
        merge(right)
 
        i = j = k = 0 
        
        while i < len(left) and j < len(right):
            if left[i] <= right[j]:
                arr[k] = left[i]
                i += 1
            else:
                arr[k] = right[j]
                j += 1
            k += 1 
        
        while i < len(left):
            arr[k] = left[i]
            i += 1
            k += 1
 
        while j < len(right):
            arr[k] = right[j]
            j += 1
            k += 1

In [13]:
#This method is just to calculate the time, if you don't need it, don't worry
def merge_algorithm(arr):
    start = time.time()
    merge(arr)
    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr

In [43]:
merge_algorithm(data)

The time of execution of above program is : 132.61866569519043 ms for a size of  17000


array([   1,    1,    1, ..., 9999, 9999, 9999])

In [21]:
merge_algorithm(dt)

The time of execution of above program is : 5.999326705932617 ms for a size of  1000


array([   6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
          6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
          6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
          6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
          6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
          6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
          6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
          6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
          6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
          6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
          6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
          6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
          6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
          6,    6,    6,    6,    6,    6,    6,   

### Algorithm of your choice

Know implement another algorithm, anyone works. Use the same size of data.

In [53]:
# it checkes if the array is sorted
def sorted(arr):
    n = len(arr)
    for i in range(0, n-1):
        if (arr[i] > arr[i+1] ):
            return False
    return True

In [54]:
# it randomly shuffles the array
def mix(arr):
    n = len(arr)
    for i in range (0,n):
        r = random.randint(0,n-1)
        arr[i], arr[r] = arr[r], arr[i]

In [55]:
#implements bogosort
def bogosort(arr):
    n= len(arr)
    while (sorted(arr)== False):
        mix(arr)

In [56]:
# it implements bogosort and shows how long it took
def bogo_algorithm(arr):
    start = time.time()
    bogosort(arr)
    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr

In [52]:
bogo_algorithm(dt)


The time of execution of above program is : 63735.87131500244 ms for a size of  10


array([2110, 3278, 3593, 3594, 4372, 5324, 6514, 6760, 9418, 9772])

### Conclusions

So, the algorithm matters! Even when the result is the same, the time it takes is important. We are in the era of Big Data, if we are not careful, some processing might take centuries!

NEVER USE BOGOSORT!!!!!!!!!!!!!